services:
  client:
    build:
      context: .
      dockerfile: DockerfileClient
    environment:
      HOSTNAME: server
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: DockerfileServer
    volumes:
      - ./phonebookdir:/home/usr/app/shared
